### PR TITLE
Crossing out of runway

### LINKED ISSUE #235: Crossing out of runways
Seen at KDEN : 
Some taxiways have "active zones" to protect runways but never cross the runway (taxiways WB an probably ED at KDEN)
So when a plane is cleared to cross after holding short of the runway, it is never seen as "crossing" (detected on the runway) nor "vacated" (crossing finished).
The runway is then unavailable for landing and other crossing planes.

### PR DESCRIPTION
**Pull request by Random-Ranger**
Fixes #235 

- Links taxi edges with active zones to their runways
- Planes cleared to cross and crossing position are checked on the runway and these linked taxiways edges

### CODE REVIEW

**Comment by felix-b** [comment]
Hey @Random-Ranger, thank you for your contribution, and welcome aboard!
This PR looks great. 
I'll test it manually tomorrow, and if everything is OK, I'll merge.
Then I'm going to apply this new detection to landing and departing aircraft as well.

**Comment by Random-Ranger** [comment]
You're welcome.
Congratulations for this great plugin. I'll be glad to do more.

I'm not sure that this new detection mechanism is relevant to landing and departing aircrafts though.

**Comment by felix-b** [comment]
@Random-Ranger GitHub automatically suggested adding "Co-authored by ... "  with your name and email to the commit message. In case you didn't intend to publicly include those details, let me know.

**Comment by felix-b** [comment]
> I'll be glad to do more.

Sure. 
You may want to join our discussion group in Slack (it's web-based among other options, so no need to install anything) 
https://join.slack.com/t/atcplugin/shared_invite/zt-ibq6w982-tM_3A7PcC0UkT5qspnpMrw

> I'm not sure that this new detection mechanism is relevant to landing and departing aircrafts though.

As far as I understand, an aircraft within a runway active zone should be considered an obstacle for takeoffs and landings. So including active zones in the detection would add to the accuracy.

**Comment by Random-Ranger** [comment]
Ok,
I was misunderstanding your point. I was focused on the detection of
aircraft by the controller.

**Comment by Random-Ranger** [comment]
> @Random-Ranger GitHub automatically suggested adding "Co-authored by ... " with your name and email to the commit message. In case you didn't intend to publicly include those details, let me know.

@felix-b could you please remove that part of the tag comment, if it's possible, i'll update my local git configuration for my next PR

**Pull request merged**
