### PR TITLE
Tower transfer

### LINKED ISSUE #245: At LFPG, TWR does not clear planes for takeoff
At LFPG, TWR does not clear planes for takeoff. They just pile up at the waiting point of departure runway 08L, waiting for takeoff clearance. I tried it three times, always with the same result. You can see in the picture two planes over each other at the waiting point.

Screenshot

### PR DESCRIPTION
**Pull request by Random-Ranger**
Fixes #245 and another bug i found watching planes taking off and landing :) 
If a plane is cleared for Line Up and Wait because someone is crossing, if another plane check in with the tower when the crossing plane has vacated the runway, the second plane is cleared for takeoff.

@felix-b The check on Windows will fail, this has been fixed in the previous PR #247

### CODE REVIEW

**Comment by felix-b** [comment]
@Random-Ranger Now the build is working but one test fails.
Since this is an "accuracy-critical" place in code, I'd also include a test that reproduces the bug.

The most effective kind of test for this code proved to be a "long-running test", which is a unit test where I simulate the interaction of several aircraft with the Tower on a timeline.

An example can be found here: https://github.com/felix-b/atc/blob/master/src/libai_test/runwayMutexSequenceTest5.cpp#L33
The file https://github.com/felix-b/atc/blob/master/src/libai_test/runwayMutexSequenceTest6.cpp is a land of blank template - you can just write the new test there.

**Comment by felix-b** [comment]
@Random-Ranger 

I admit that test infrastructure for SimpleRunwayMutex requires introduction/explanation.
And the word "Simple" in the name is kind of ironic (as it always happens to everything named "simple")

Let me know how what you prefer to do - do you want me to document the test infrastructure, or you want me to add the tests.

**Comment by Random-Ranger** [comment]
@felix-b 

I just saw your message about the failed tests.
I will check and add some tests. I'll ask if I need more informations.

**Comment by Random-Ranger** [comment]
@felix-b 
I took a look at the long running test infrastructure and I found it very impressive.
Some comments and/or a wiki page to introduce it could be beneficial but it's pretty self explanatory.

As for the bug, there was indeed a problem in the test that I had added. I had a little trouble pinpointing the exact cause of the problem but eventually I got it :

-  A plane arrives at the holding point of its departure runway and is cleared for line up and wait (because of a crossing plane)
- The conditions that prevented it to get a take off clearance disappears before it is on the runway
- Another plane checks in with the tower at the holding point before the first plane is on the runway : the second plane is cleared for takeoff

The fix is coming

**Comment by felix-b** [comment]
@Random-Ranger 
Great - if you have any questions, let me know

**Comment by Random-Ranger** [comment]
@felix-b 
No questions for now. The test that I added in 121d81e is not very complicated but it failed without the fix and now it passes.

Let me know if it's enough for you.

**Review by felix-b — APPROVED** [review]
@Random-Ranger 
Sorry I've overlooked the last commit
That's perfect - I'll manual-test and merge

P.S. I'm starting to think about creating an automated sanity test in X-Plane...

**Pull request merged**
